version: '3.8'

# Development overrides for docker-compose.yml
# Use: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: deps  # Only build to deps stage for development
    volumes:
      - ./backend:/app
      - ./backend/node_modules:/app/node_modules
      - ./data:/app/data
    environment:
      NODE_ENV: development
      DEBUG: "*"
    command: npm run dev

  frontend:
    build:
      context: ./frontend  
      dockerfile: Dockerfile
      target: deps  # Only build to deps stage for development
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    environment:
      NODE_ENV: development
    command: npm run dev