# GitHub Pages Configuration for CensusChat
title: "CensusChat - Natural Language Census Data Query Platform"
description: "Democratize access to US Census data through natural language queries. Ask questions in plain English, get insights in seconds."
url: "https://hollandkevint.github.io"
baseurl: "/CensusChat"

# GitHub Pages settings
theme: null
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Site settings
author:
  name: "CensusChat Team"
  email: "hello@censuschat.org"

# Social links
github_username: hollandkevint
repository: "hollandkevint/CensusChat"

# Analytics (placeholder for future)
# google_analytics: UA-XXXXXXXX-X

# SEO settings
lang: en_US
twitter:
  card: summary_large_image
  username: censuschat

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  style: compressed

# Include/Exclude files
include:
  - _pages
  - assets

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - gemfiles
  - .gitignore
  - .git

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "doc"

# Custom variables
project:
  name: "CensusChat"
  tagline: "Natural Language Census Data Query Platform"
  version: "0.1.0"
  status: "Early Development"
  methodology: "BMAD B2B Data Products Framework"
  
# Features
features:
  - name: "Natural Language Queries"
    description: "Ask questions in plain English"
    icon: "🗣️"
  - name: "Lightning Fast"
    description: "Sub-second responses on 11M+ records"
    icon: "⚡"
  - name: "Security First"
    description: "SQL validation restricts to SELECT only"
    icon: "🛡️"
  - name: "Comprehensive Data"
    description: "Access to 250+ Census tables"
    icon: "📊"
  - name: "Open Source"
    description: "Community-driven development"
    icon: "🔓"
  - name: "Freemium Model"
    description: "Free tier with affordable pro plans"
    icon: "💰"

# Statistics
stats:
  records: "11M+"
  response_time: "<2s"
  data_tables: "250+"
  target_market: "560K"

# Navigation
navigation:
  - name: "Home"
    url: "/"
  - name: "Features"
    url: "/#features"
  - name: "About"
    url: "/#about"
  - name: "Community"
    url: "/#community"
  - name: "GitHub"
    url: "https://github.com/hollandkevint/CensusChat"
    external: true