version: '3.8'

# Demo-ready Docker Compose for CensusChat
# Optimized for localhost deployment and demoing

services:
  # PostgreSQL Database for user data and sessions
  postgres:
    image: postgres:16-alpine
    container_name: censuschat-postgres-demo
    restart: unless-stopped
    environment:
      POSTGRES_USER: censuschat_user
      POSTGRES_PASSWORD: censuschat_demo_2024
      POSTGRES_DB: censuschat_demo
    ports:
      - "5432:5432"
    volumes:
      - postgres_demo_data:/var/lib/postgresql/data
      - ./test-data/postgres-init:/docker-entrypoint-initdb.d
    networks:
      - censuschat-demo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U censuschat_user -d censuschat_demo"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.track=all
      -c log_statement=all
      -c log_min_duration_statement=1000

  # Redis Cache for API responses and session storage
  redis:
    image: redis:7-alpine
    container_name: censuschat-redis-demo
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_demo_data:/data
    networks:
      - censuschat-demo
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API with DuckDB integration
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: deps  # Use deps stage for development
    container_name: censuschat-backend-demo
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      PORT: 3001
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: censuschat_demo
      POSTGRES_USER: censuschat_user
      POSTGRES_PASSWORD: censuschat_demo_2024
      POSTGRES_SSL: false
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      DUCKDB_PATH: /app/data/census.duckdb
      DUCKDB_MEMORY: false
      JWT_SECRET: demo-jwt-secret-key-for-censuschat-2024
      JWT_EXPIRES_IN: 24h
      JWT_REFRESH_EXPIRES_IN: 7d
      CENSUS_API_URL: https://api.census.gov
      CENSUS_API_KEY: ""
      USE_LIVE_CENSUS_API: false
      CENSUS_CACHE_TTL: 3600
      CENSUS_API_REQUESTS_PER_HOUR: 400
      CORS_ORIGIN: http://localhost:3000,http://localhost:3001
      DEBUG: "*"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./data:/app/data
      - ./test-data:/app/test-data
      - ./temp:/app/temp
    networks:
      - censuschat-demo
    command: npm run dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: deps  # Use deps stage for development
    container_name: censuschat-frontend-demo
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3001/api/v1
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - censuschat-demo
    command: npm run dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  # DuckDB Data Initialization Service
  duckdb-init:
    image: node:20-alpine
    container_name: censuschat-duckdb-init
    restart: "no"
    environment:
      DUCKDB_PATH: /app/data/census.duckdb
    volumes:
      - ./backend:/app
      - ./data:/app/data
      - ./test-data:/app/test-data
    networks:
      - censuschat-demo
    depends_on:
      - backend
    command: >
      sh -c "
        echo '🦆 Initializing DuckDB with demo data...' &&
        cd /app &&
        npm install &&
        node -e \"
          const { execSync } = require('child_process');
          try {
            execSync('npm run build', { stdio: 'inherit' });
            console.log('✅ Backend built successfully');
          } catch (error) {
            console.log('⚠️  Build failed, continuing with dev mode');
          }
        \" &&
        echo '📊 Setting up demo data...' &&
        node -e \"
          const fs = require('fs');
          const path = require('path');
          
          // Create data directory if it doesn't exist
          const dataDir = '/app/data';
          if (!fs.existsSync(dataDir)) {
            fs.mkdirSync(dataDir, { recursive: true });
          }
          
          // Create temp directory for exports
          const tempDir = '/app/temp/exports';
          if (!fs.existsSync(tempDir)) {
            fs.mkdirSync(tempDir, { recursive: true });
          }
          
          console.log('✅ Directories created');
        \" &&
        echo '🎉 DuckDB initialization complete!'
      "

  # Demo Data Seeding Service
  demo-seed:
    image: node:20-alpine
    container_name: censuschat-demo-seed
    restart: "no"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: censuschat_demo
      POSTGRES_USER: censuschat_user
      POSTGRES_PASSWORD: censuschat_demo_2024
      DUCKDB_PATH: /app/data/census.duckdb
    volumes:
      - ./backend:/app
      - ./data:/app/data
      - ./test-data:/app/test-data
    networks:
      - censuschat-demo
    depends_on:
      postgres:
        condition: service_healthy
      duckdb-init:
        condition: service_completed_successfully
    command: >
      sh -c "
        echo '🌱 Seeding demo data...' &&
        cd /app &&
        sleep 5 &&
        node -e \"
          const { execSync } = require('child_process');
          try {
            // Run the demo data seeding script
            execSync('node dist/scripts/seedTestData.js', { stdio: 'inherit' });
            console.log('✅ Demo data seeded successfully');
          } catch (error) {
            console.log('⚠️  Demo seeding failed, using fallback data');
            // Create minimal demo data
            const fs = require('fs');
            const path = require('path');
            
            const demoData = {
              message: 'Demo data loaded',
              timestamp: new Date().toISOString(),
              status: 'ready'
            };
            
            fs.writeFileSync('/app/data/demo-status.json', JSON.stringify(demoData, null, 2));
            console.log('✅ Fallback demo data created');
          }
        \" &&
        echo '🎉 Demo data seeding complete!'
      "

volumes:
  postgres_demo_data:
    driver: local
  redis_demo_data:
    driver: local

networks:
  censuschat-demo:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

